version: "3.3"

services:
  db:
    image: postgres:13.1
    container_name: db_lumi
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./dockerfiles/postgresql/data:/var/lib/postgresql/data
    restart: on-failure
  
  app:
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/app
    env_file:
      - .env
    expose:
      - 8000
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - db
    
    
  web:
    build:
      context: ./web
    volumes:
      - ./web:/usr/web
    env_file:
      - .env
    expose:
      - 3000
    ports:
      - "3000:3000"
    restart: on-failure