version: "3.3"

services:
  db:
    image: postgres:13.1
    container_name: db_lumi
    env_file:
      - .env
    ports:
      - "5434:5434"
    volumes:
      - ./dockerfiles/postgresql/data:/var/lib/postgresql/data
    restart: on-failure
    command: -p 5434
  
  app:
    build:
      context: ./backend
    env_file:
      - .env
    expose:
      - 3005
    ports:
      - "3005:3005"
    restart: on-failure
    depends_on:
      - db
    