name: mobile
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=2.18.2 <3.0.0'

dependencies:
    flutter:
        sdk: flutter


    auto_route: ^5.0.1
    flutter_bloc: ^8.1.1
    hydrated_bloc: ^8.1.0
    equatable: ^2.0.5
    provider: ^6.0.3
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    sentry_flutter: ^6.11.2
    logger: ^1.1.0
    get_it: ^7.2.0
    dio: ^4.0.6
    dartz: ^0.10.1
    freezed_annotation: ^2.1.0
    json_annotation: ^4.7.0
    loggy: ^2.0.1+1
    collection: ^1.16.0
    path: ^1.8.2
    path_provider: ^2.0.11
    intl: ^0.17.0
    email_validator: ^2.1.16
    image_picker: ^0.8.6
    permission_handler: ^10.2.0
    mime: ^1.0.2

    # UI
    curved_progress_bar: ^1.0.2
    flutter_feather_icons: ^2.0.0+1
    flutter_svg: ^1.1.6

    flutter_localizations:
        sdk: flutter


dev_dependencies:
    flutter_test:
        sdk: flutter

    auto_route_generator: ^5.0.2
    hive_generator: ^1.1.3
    build_runner:
    freezed:
    json_serializable:
    flutter_lints: ^2.0.1
    flutter_launcher_icons: ^0.10.0

flutter:

    uses-material-design: true

    assets:
        - assets/fonts/
        - assets/icons/
    fonts:
        - family: Inter
          fonts:
            - asset: assets/fonts/Inter-ExtraLight.ttf
              weight: 100
            - asset: assets/fonts/Inter-Thin.ttf
              weight: 200
            - asset: assets/fonts/Inter-Light.ttf
              weight: 300
            - asset: assets/fonts/Inter-Regular.ttf
              weight: 400
            - asset: assets/fonts/Inter-Medium.ttf
              weight: 500
            - asset: assets/fonts/Inter-Semibold.ttf
              weight: 600
            - asset: assets/fonts/Inter-Bold.ttf
              weight: 700
            - asset: assets/fonts/Inter-Black.ttf
              weight: 800
            - asset: assets/fonts/Inter-ExtraBold.ttf
              weight: 900
